  <SELECT name="TitleColor">
       <option value='' selected>±ÍÃ‚—’…´</option>
          <option style="COLOR: #ff0000; BACKGROUND-COLOR: #ff0000" value=#ff0000 <%if(TitleColor=="#ff0000") Response.Write("selected");%>>#ff0000</option>
          <option style="COLOR: #f0f8ff; BACKGROUND-COLOR: #f0f8ff" value=#F0F8FF <%if(TitleColor=="#F0F8FF") Response.Write("selected");%>>#F0F8FF</option>
          <option style="COLOR: #faebd7; BACKGROUND-COLOR: #faebd7" value=#FAEBD7 <%if(TitleColor=="#FAEBD7") Response.Write("selected");%>>#FAEBD7</option>
          <option style="COLOR: #00ffff; BACKGROUND-COLOR: #00ffff" value=#00FFFF <%if(TitleColor=="#00FFFF") Response.Write("selected");%>>#00FFFF</option>
          <option style="COLOR: #7fffd4; BACKGROUND-COLOR: #7fffd4" value=#7FFFD4 <%if(TitleColor=="#7FFFD4") Response.Write("selected");%>>#7FFFD4</option>
          <option style="COLOR: #f0ffff; BACKGROUND-COLOR: #f0ffff" value=#F0FFFF <%if(TitleColor=="#F0FFFF") Response.Write("selected");%>>#F0FFFF</option>
          <option style="COLOR: #f5f5dc; BACKGROUND-COLOR: #f5f5dc" value=#F5F5DC <%if(TitleColor=="#F5F5DC") Response.Write("selected");%>>#F5F5DC</option>
          <option style="COLOR: #ffe4c4; BACKGROUND-COLOR: #ffe4c4" value=#FFE4C4 <%if(TitleColor=="#FFE4C4") Response.Write("selected");%>>#FFE4C4</option>
          <option style="COLOR: #000000; BACKGROUND-COLOR: #000000" value=#000000 <%if(TitleColor=="#000000") Response.Write("selected");%>>#000000</option>
          <option style="COLOR: #ffebcd; BACKGROUND-COLOR: #ffebcd" value=#FFEBCD <%if(TitleColor=="#FFEBCD") Response.Write("selected");%>>#FFEBCD</option>
          <option style="COLOR: #0000ff; BACKGROUND-COLOR: #0000ff" value=#0000FF <%if(TitleColor=="#0000FF") Response.Write("selected");%>>#0000FF</option>
          <option style="COLOR: #8a2be2; BACKGROUND-COLOR: #8a2be2" value=#8A2BE2 <%if(TitleColor=="#8A2BE2") Response.Write("selected");%>>#8A2BE2</option>
          <option style="COLOR: #a52a2a; BACKGROUND-COLOR: #a52a2a" value=#A52A2A <%if(TitleColor=="#A52A2A") Response.Write("selected");%>>#A52A2A</option>
          <option style="COLOR: #deb887; BACKGROUND-COLOR: #deb887" value=#DEB887 <%if(TitleColor=="#DEB887") Response.Write("selected");%>>#DEB887</option>
          <option style="COLOR: #5f9ea0; BACKGROUND-COLOR: #5f9ea0" value=#5F9EA0 <%if(TitleColor=="#5F9EA0") Response.Write("selected");%>>#5F9EA0</option>
          <option style="COLOR: #7fff00; BACKGROUND-COLOR: #7fff00" value=#7FFF00 <%if(TitleColor=="#7FFF00") Response.Write("selected");%>>#7FFF00</option>
          <option style="COLOR: #d2691e; BACKGROUND-COLOR: #d2691e" value=#D2691E <%if(TitleColor=="#D2691E") Response.Write("selected");%>>#D2691E</option>
          <option style="COLOR: #ff7f50; BACKGROUND-COLOR: #ff7f50" value=#FF7F50 <%if(TitleColor=="#FF7F50") Response.Write("selected");%>>#FF7F50</option>
          <option style="COLOR: #6495ed; BACKGROUND-COLOR: #6495ed" value=#6495ED <%if(TitleColor=="#6495ED") Response.Write("selected");%>>#6495ED</option>
          <option style="COLOR: #fff8dc; BACKGROUND-COLOR: #fff8dc" value=#FFF8DC <%if(TitleColor=="#FFF8DC") Response.Write("selected");%>>#FFF8DC</option>
          <option style="COLOR: #dc143c; BACKGROUND-COLOR: #dc143c" value=#DC143C <%if(TitleColor=="#DC143C") Response.Write("selected");%>>#DC143C</option>
          <option style="COLOR: #00ffff; BACKGROUND-COLOR: #00ffff" value=#00FFFF <%if(TitleColor=="#00FFFF") Response.Write("selected");%>>#00FFFF</option>
          <option style="COLOR: #00008b; BACKGROUND-COLOR: #00008b" value=#00008B <%if(TitleColor=="#00008B") Response.Write("selected");%>>#00008B</option>
          <option style="COLOR: #008b8b; BACKGROUND-COLOR: #008b8b" value=#008B8B <%if(TitleColor=="#008B8B") Response.Write("selected");%>>#008B8B</option>
          <option style="COLOR: #b8860b; BACKGROUND-COLOR: #b8860b" value=#B8860B <%if(TitleColor=="#B8860B") Response.Write("selected");%>>#B8860B</option>
          <option style="COLOR: #a9a9a9; BACKGROUND-COLOR: #a9a9a9" value=#A9A9A9 <%if(TitleColor=="#A9A9A9") Response.Write("selected");%>>#A9A9A9</option>
          <option style="COLOR: #006400; BACKGROUND-COLOR: #006400" value=#006400 <%if(TitleColor=="#006400") Response.Write("selected");%>>#006400</option>
          <option style="COLOR: #bdb76b; BACKGROUND-COLOR: #bdb76b" value=#BDB76B <%if(TitleColor=="#BDB76B") Response.Write("selected");%>>#BDB76B</option>
          <option style="COLOR: #8b008b; BACKGROUND-COLOR: #8b008b" value=#8B008B <%if(TitleColor=="#8B008B") Response.Write("selected");%>>#8B008B</option>
          <option style="COLOR: #556b2f; BACKGROUND-COLOR: #556b2f" value=#556B2F <%if(TitleColor=="#556B2F") Response.Write("selected");%>>#556B2F</option>
          <option style="COLOR: #ff8c00; BACKGROUND-COLOR: #ff8c00" value=#FF8C00 <%if(TitleColor=="#FF8C00") Response.Write("selected");%>>#FF8C00</option>
          <option style="COLOR: #9932cc; BACKGROUND-COLOR: #9932cc" value=#9932CC <%if(TitleColor=="#9932CC") Response.Write("selected");%>>#9932CC</option>
          <option style="COLOR: #8b0000; BACKGROUND-COLOR: #8b0000" value=#8B0000 <%if(TitleColor=="#8B0000") Response.Write("selected");%>>#8B0000</option>
          <option style="COLOR: #e9967a; BACKGROUND-COLOR: #e9967a" value=#E9967A <%if(TitleColor=="#E9967A") Response.Write("selected");%>>#E9967A</option>
          <option style="COLOR: #8fbc8f; BACKGROUND-COLOR: #8fbc8f" value=#8FBC8F <%if(TitleColor=="#8FBC8F") Response.Write("selected");%>>#8FBC8F</option>
          <option style="COLOR: #483d8b; BACKGROUND-COLOR: #483d8b" value=#483D8B <%if(TitleColor=="#483D8B") Response.Write("selected");%>>#483D8B</option>
          <option style="COLOR: #2f4f4f; BACKGROUND-COLOR: #2f4f4f" value=#2F4F4F <%if(TitleColor=="#2F4F4F") Response.Write("selected");%>>#2F4F4F</option>
          <option style="COLOR: #00ced1; BACKGROUND-COLOR: #00ced1" value=#00CED1 <%if(TitleColor=="#00CED1") Response.Write("selected");%>>#00CED1</option>
          <option style="COLOR: #9400d3; BACKGROUND-COLOR: #9400d3" value=#9400D3 <%if(TitleColor=="#9400D3") Response.Write("selected");%>>#9400D3</option>
          <option style="COLOR: #ff1493; BACKGROUND-COLOR: #ff1493" value=#FF1493 <%if(TitleColor=="#FF1493") Response.Write("selected");%>>#FF1493</option>
          <option style="COLOR: #00bfff; BACKGROUND-COLOR: #00bfff" value=#00BFFF <%if(TitleColor=="#00BFFF") Response.Write("selected");%>>#00BFFF</option>
          <option style="COLOR: #696969; BACKGROUND-COLOR: #696969" value=#696969 <%if(TitleColor=="#696969") Response.Write("selected");%>>#696969</option>
          <option style="COLOR: #1e90ff; BACKGROUND-COLOR: #1e90ff" value=#1E90FF <%if(TitleColor=="#1E90FF") Response.Write("selected");%>>#1E90FF</option>
          <option style="COLOR: #b22222; BACKGROUND-COLOR: #b22222" value=#B22222 <%if(TitleColor=="#B22222") Response.Write("selected");%>>#B22222</option>
          <option style="COLOR: #fffaf0; BACKGROUND-COLOR: #fffaf0" value=#FFFAF0 <%if(TitleColor=="#FFFAF0") Response.Write("selected");%>>#FFFAF0</option>
          <option style="COLOR: #228b22; BACKGROUND-COLOR: #228b22" value=#228B22 <%if(TitleColor=="#228B22") Response.Write("selected");%>>#228B22</option>
          <option style="COLOR: #ff00ff; BACKGROUND-COLOR: #ff00ff" value=#FF00FF <%if(TitleColor=="#FF00FF") Response.Write("selected");%>>#FF00FF</option>
          <option style="COLOR: #dcdcdc; BACKGROUND-COLOR: #dcdcdc" value=#DCDCDC <%if(TitleColor=="#DCDCDC") Response.Write("selected");%>>#DCDCDC</option>
          <option style="COLOR: #f8f8ff; BACKGROUND-COLOR: #f8f8ff" value=#F8F8FF <%if(TitleColor=="#F8F8FF") Response.Write("selected");%>>#F8F8FF</option>
          <option style="COLOR: #ffd700; BACKGROUND-COLOR: #ffd700" value=#FFD700 <%if(TitleColor=="#FFD700") Response.Write("selected");%>>#FFD700</option>
          <option style="COLOR: #daa520; BACKGROUND-COLOR: #daa520" value=#DAA520 <%if(TitleColor=="#DAA520") Response.Write("selected");%>>#DAA520</option>
          <option style="COLOR: #808080; BACKGROUND-COLOR: #808080" value=#808080 <%if(TitleColor=="#808080") Response.Write("selected");%>>#808080</option>
          <option style="COLOR: #008000; BACKGROUND-COLOR: #008000" value=#008000 <%if(TitleColor=="#008000") Response.Write("selected");%>>#008000</option>
          <option style="COLOR: #adff2f; BACKGROUND-COLOR: #adff2f" value=#ADFF2F <%if(TitleColor=="#ADFF2F") Response.Write("selected");%>>#ADFF2F</option>
          <option style="COLOR: #f0fff0; BACKGROUND-COLOR: #f0fff0" value=#F0FFF0 <%if(TitleColor=="#F0FFF0") Response.Write("selected");%>>#F0FFF0</option>
          <option style="COLOR: #ff69b4; BACKGROUND-COLOR: #ff69b4" value=#FF69B4 <%if(TitleColor=="#FF69B4") Response.Write("selected");%>>#FF69B4</option>
          <option style="COLOR: #cd5c5c; BACKGROUND-COLOR: #cd5c5c" value=#CD5C5C <%if(TitleColor=="#CD5C5C") Response.Write("selected");%>>#CD5C5C</option>
          <option style="COLOR: #4b0082; BACKGROUND-COLOR: #4b0082" value=#4B0082 <%if(TitleColor=="#4B0082") Response.Write("selected");%>>#4B0082</option>
          <option style="COLOR: #fffff0; BACKGROUND-COLOR: #fffff0" value=#FFFFF0 <%if(TitleColor=="#FFFFF0") Response.Write("selected");%>>#FFFFF0</option>
          <option style="COLOR: #f0e68c; BACKGROUND-COLOR: #f0e68c" value=#F0E68C <%if(TitleColor=="#F0E68C") Response.Write("selected");%>>#F0E68C</option>
          <option style="COLOR: #e6e6fa; BACKGROUND-COLOR: #e6e6fa" value=#E6E6FA <%if(TitleColor=="#E6E6FA") Response.Write("selected");%>>#E6E6FA</option>
          <option style="COLOR: #fff0f5; BACKGROUND-COLOR: #fff0f5" value=#FFF0F5 <%if(TitleColor=="#FFF0F5") Response.Write("selected");%>>#FFF0F5</option>
          <option style="COLOR: #7cfc00; BACKGROUND-COLOR: #7cfc00" value=#7CFC00 <%if(TitleColor=="#7CFC00") Response.Write("selected");%>>#7CFC00</option>
          <option style="COLOR: #fffacd; BACKGROUND-COLOR: #fffacd" value=#FFFACD <%if(TitleColor=="#FFFACD") Response.Write("selected");%>>#FFFACD</option>
          <option style="COLOR: #add8e6; BACKGROUND-COLOR: #add8e6" value=#ADD8E6 <%if(TitleColor=="#ADD8E6") Response.Write("selected");%>>#ADD8E6</option>
          <option style="COLOR: #f08080; BACKGROUND-COLOR: #f08080" value=#F08080 <%if(TitleColor=="#F08080") Response.Write("selected");%>>#F08080</option>
          <option style="COLOR: #e0ffff; BACKGROUND-COLOR: #e0ffff" value=#E0FFFF <%if(TitleColor=="#E0FFFF") Response.Write("selected");%>>#E0FFFF</option>
          <option style="COLOR: #fafad2; BACKGROUND-COLOR: #fafad2" value=#FAFAD2 <%if(TitleColor=="#FAFAD2") Response.Write("selected");%>>#FAFAD2</option>
          <option style="COLOR: #90ee90; BACKGROUND-COLOR: #90ee90" value=#90EE90 <%if(TitleColor=="#90EE90") Response.Write("selected");%>>#90EE90</option>
          <option style="COLOR: #d3d3d3; BACKGROUND-COLOR: #d3d3d3" value=#D3D3D3 <%if(TitleColor=="#D3D3D3") Response.Write("selected");%>>#D3D3D3</option>
          <option style="COLOR: #ffb6c1; BACKGROUND-COLOR: #ffb6c1" value=#FFB6C1 <%if(TitleColor=="#FFB6C1") Response.Write("selected");%>>#FFB6C1</option>
          <option style="COLOR: #ffa07a; BACKGROUND-COLOR: #ffa07a" value=#FFA07A <%if(TitleColor=="#FFA07A") Response.Write("selected");%>>#FFA07A</option>
          <option style="COLOR: #20b2aa; BACKGROUND-COLOR: #20b2aa" value=#20B2AA <%if(TitleColor=="#20B2AA") Response.Write("selected");%>>#20B2AA</option>
          <option style="COLOR: #87cefa; BACKGROUND-COLOR: #87cefa" value=#87CEFA <%if(TitleColor=="#87CEFA") Response.Write("selected");%>>#87CEFA</option>
          <option style="COLOR: #778899; BACKGROUND-COLOR: #778899" value=#778899 <%if(TitleColor=="#778899") Response.Write("selected");%>>#778899</option>
          <option style="COLOR: #b0c4de; BACKGROUND-COLOR: #b0c4de" value=#B0C4DE <%if(TitleColor=="#B0C4DE") Response.Write("selected");%>>#B0C4DE</option>
          <option style="COLOR: #ffffe0; BACKGROUND-COLOR: #ffffe0" value=#FFFFE0 <%if(TitleColor=="#FFFFE0") Response.Write("selected");%>>#FFFFE0</option>
          <option style="COLOR: #00ff00; BACKGROUND-COLOR: #00ff00" value=#00FF00 <%if(TitleColor=="#00FF00") Response.Write("selected");%>>#00FF00</option>
          <option style="COLOR: #32cd32; BACKGROUND-COLOR: #32cd32" value=#32CD32 <%if(TitleColor=="#32CD32") Response.Write("selected");%>>#32CD32</option>
          <option style="COLOR: #faf0e6; BACKGROUND-COLOR: #faf0e6" value=#FAF0E6 <%if(TitleColor=="#FAF0E6") Response.Write("selected");%>>#FAF0E6</option>
          <option style="COLOR: #ff00ff; BACKGROUND-COLOR: #ff00ff" value=#FF00FF <%if(TitleColor=="#FF00FF") Response.Write("selected");%>>#FF00FF</option>
          <option style="COLOR: #800000; BACKGROUND-COLOR: #800000" value=#800000 <%if(TitleColor=="#800000") Response.Write("selected");%>>#800000</option>
          <option style="COLOR: #66cdaa; BACKGROUND-COLOR: #66cdaa" value=#66CDAA <%if(TitleColor=="#66CDAA") Response.Write("selected");%>>#66CDAA</option>
          <option style="COLOR: #0000cd; BACKGROUND-COLOR: #0000cd" value=#0000CD <%if(TitleColor=="#0000CD") Response.Write("selected");%>>#0000CD</option>
          <option style="COLOR: #ba55d3; BACKGROUND-COLOR: #ba55d3" value=#BA55D3 <%if(TitleColor=="#BA55D3") Response.Write("selected");%>>#BA55D3</option>
          <option style="COLOR: #9370db; BACKGROUND-COLOR: #9370db" value=#9370DB <%if(TitleColor=="#9370DB") Response.Write("selected");%>>#9370DB</option>
          <option style="COLOR: #3cb371; BACKGROUND-COLOR: #3cb371" value=#3CB371 <%if(TitleColor=="#3CB371") Response.Write("selected");%>>#3CB371</option>
          <option style="COLOR: #7b68ee; BACKGROUND-COLOR: #7b68ee" value=#7B68EE <%if(TitleColor=="#7B68EE") Response.Write("selected");%>>#7B68EE</option>
          <option style="COLOR: #00fa9a; BACKGROUND-COLOR: #00fa9a" value=#00FA9A <%if(TitleColor=="#00FA9A") Response.Write("selected");%>>#00FA9A</option>
          <option style="COLOR: #48d1cc; BACKGROUND-COLOR: #48d1cc" value=#48D1CC <%if(TitleColor=="#48D1CC") Response.Write("selected");%>>#48D1CC</option>
          <option style="COLOR: #c71585; BACKGROUND-COLOR: #c71585" value=#C71585 <%if(TitleColor=="#C71585") Response.Write("selected");%>>#C71585</option>
          <option style="COLOR: #191970; BACKGROUND-COLOR: #191970" value=#191970 <%if(TitleColor=="#191970") Response.Write("selected");%>>#191970</option>
          <option style="COLOR: #f5fffa; BACKGROUND-COLOR: #f5fffa" value=#F5FFFA <%if(TitleColor=="#F5FFFA") Response.Write("selected");%>>#F5FFFA</option>
          <option style="COLOR: #ffe4e1; BACKGROUND-COLOR: #ffe4e1" value=#FFE4E1 <%if(TitleColor=="#FFE4E1") Response.Write("selected");%>>#FFE4E1</option>
          <option style="COLOR: #ffe4b5; BACKGROUND-COLOR: #ffe4b5" value=#FFE4B5 <%if(TitleColor=="#FFE4B5") Response.Write("selected");%>>#FFE4B5</option>
          <option style="COLOR: #ffdead; BACKGROUND-COLOR: #ffdead" value=#FFDEAD <%if(TitleColor=="#FFDEAD") Response.Write("selected");%>>#FFDEAD</option>
          <option style="COLOR: #000080; BACKGROUND-COLOR: #000080" value=#000080 <%if(TitleColor=="#000080") Response.Write("selected");%>>#000080</option>
          <option style="COLOR: #fdf5e6; BACKGROUND-COLOR: #fdf5e6" value=#FDF5E6 <%if(TitleColor=="#FDF5E6") Response.Write("selected");%>>#FDF5E6</option>
          <option style="COLOR: #808000; BACKGROUND-COLOR: #808000" value=#808000 <%if(TitleColor=="#808000") Response.Write("selected");%>>#808000</option>
          <option style="COLOR: #6b8e23; BACKGROUND-COLOR: #6b8e23" value=#6B8E23 <%if(TitleColor=="#6B8E23") Response.Write("selected");%>>#6B8E23</option>
          <option style="COLOR: #ffa500; BACKGROUND-COLOR: #ffa500" value=#FFA500 <%if(TitleColor=="#FFA500") Response.Write("selected");%>>#FFA500</option>
          <option style="COLOR: #ff4500; BACKGROUND-COLOR: #ff4500" value=#FF4500 <%if(TitleColor=="#FF4500") Response.Write("selected");%>>#FF4500</option>
          <option style="COLOR: #da70d6; BACKGROUND-COLOR: #da70d6" value=#DA70D6 <%if(TitleColor=="#DA70D6") Response.Write("selected");%>>#DA70D6</option>
          <option style="COLOR: #eee8aa; BACKGROUND-COLOR: #eee8aa" value=#EEE8AA <%if(TitleColor=="#EEE8AA") Response.Write("selected");%>>#EEE8AA</option>
          <option style="COLOR: #98fb98; BACKGROUND-COLOR: #98fb98" value=#98FB98 <%if(TitleColor=="#98FB98") Response.Write("selected");%>>#98FB98</option>
          <option style="COLOR: #afeeee; BACKGROUND-COLOR: #afeeee" value=#AFEEEE <%if(TitleColor=="#AFEEEE") Response.Write("selected");%>>#AFEEEE</option>
          <option style="COLOR: #db7093; BACKGROUND-COLOR: #db7093" value=#DB7093 <%if(TitleColor=="#DB7093") Response.Write("selected");%>>#DB7093</option>
          <option style="COLOR: #ffefd5; BACKGROUND-COLOR: #ffefd5" value=#FFEFD5 <%if(TitleColor=="#FFEFD5") Response.Write("selected");%>>#FFEFD5</option>
          <option style="COLOR: #ffdab9; BACKGROUND-COLOR: #ffdab9" value=#FFDAB9 <%if(TitleColor=="#FFDAB9") Response.Write("selected");%>>#FFDAB9</option>
          <option style="COLOR: #cd853f; BACKGROUND-COLOR: #cd853f" value=#CD853F <%if(TitleColor=="#CD853F") Response.Write("selected");%>>#CD853F</option>
          <option style="COLOR: #ffc0cb; BACKGROUND-COLOR: #ffc0cb" value=#FFC0CB <%if(TitleColor=="#FFC0CB") Response.Write("selected");%>>#FFC0CB</option>
          <option style="COLOR: #dda0dd; BACKGROUND-COLOR: #dda0dd" value=#DDA0DD <%if(TitleColor=="#DDA0DD") Response.Write("selected");%>>#DDA0DD</option>
          <option style="COLOR: #b0e0e6; BACKGROUND-COLOR: #b0e0e6" value=#B0E0E6 <%if(TitleColor=="#B0E0E6") Response.Write("selected");%>>#B0E0E6</option>
          <option style="COLOR: #800080; BACKGROUND-COLOR: #800080" value=#800080 <%if(TitleColor=="#800080") Response.Write("selected");%>>#800080</option>
          <option style="COLOR: #ff0000; BACKGROUND-COLOR: #ff0000" value=#FF0000 <%if(TitleColor=="#FF0000") Response.Write("selected");%>>#FF0000</option>
          <option style="COLOR: #bc8f8f; BACKGROUND-COLOR: #bc8f8f" value=#BC8F8F <%if(TitleColor=="#BC8F8F") Response.Write("selected");%>>#BC8F8F</option>
          <option style="COLOR: #4169e1; BACKGROUND-COLOR: #4169e1" value=#4169E1 <%if(TitleColor=="#4169E1") Response.Write("selected");%>>#4169E1</option>
          <option style="COLOR: #8b4513; BACKGROUND-COLOR: #8b4513" value=#8B4513 <%if(TitleColor=="#8B4513") Response.Write("selected");%>>#8B4513</option>
          <option style="COLOR: #fa8072; BACKGROUND-COLOR: #fa8072" value=#FA8072 <%if(TitleColor=="#FA8072") Response.Write("selected");%>>#FA8072</option>
          <option style="COLOR: #f4a460; BACKGROUND-COLOR: #f4a460" value=#F4A460 <%if(TitleColor=="#F4A460") Response.Write("selected");%>>#F4A460</option>
          <option style="COLOR: #2e8b57; BACKGROUND-COLOR: #2e8b57" value=#2E8B57 <%if(TitleColor=="#2E8B57") Response.Write("selected");%>>#2E8B57</option>
          <option style="COLOR: #fff5ee; BACKGROUND-COLOR: #fff5ee" value=#FFF5EE <%if(TitleColor=="#FFF5EE") Response.Write("selected");%>>#FFF5EE</option>
          <option style="COLOR: #a0522d; BACKGROUND-COLOR: #a0522d" value=#A0522D <%if(TitleColor=="#A0522D") Response.Write("selected");%>>#A0522D</option>
          <option style="COLOR: #c0c0c0; BACKGROUND-COLOR: #c0c0c0" value=#C0C0C0 <%if(TitleColor=="#C0C0C0") Response.Write("selected");%>>#C0C0C0</option>
          <option style="COLOR: #87ceeb; BACKGROUND-COLOR: #87ceeb" value=#87CEEB <%if(TitleColor=="#87CEEB") Response.Write("selected");%>>#87CEEB</option>
          <option style="COLOR: #6a5acd; BACKGROUND-COLOR: #6a5acd" value=#6A5ACD <%if(TitleColor=="#6A5ACD") Response.Write("selected");%>>#6A5ACD</option>
          <option style="COLOR: #708090; BACKGROUND-COLOR: #708090" value=#708090 <%if(TitleColor=="#708090") Response.Write("selected");%>>#708090</option>
          <option style="COLOR: #fffafa; BACKGROUND-COLOR: #fffafa" value=#FFFAFA <%if(TitleColor=="#FFFAFA") Response.Write("selected");%>>#FFFAFA</option>
          <option style="COLOR: #00ff7f; BACKGROUND-COLOR: #00ff7f" value=#00FF7F <%if(TitleColor=="#00FF7F") Response.Write("selected");%>>#00FF7F</option>
          <option style="COLOR: #4682b4; BACKGROUND-COLOR: #4682b4" value=#4682B4 <%if(TitleColor=="#4682B4") Response.Write("selected");%>>#4682B4</option>
          <option style="COLOR: #d2b48c; BACKGROUND-COLOR: #d2b48c" value=#D2B48C <%if(TitleColor=="#D2B48C") Response.Write("selected");%>>#D2B48C</option>
          <option style="COLOR: #008080; BACKGROUND-COLOR: #008080" value=#008080 <%if(TitleColor=="#008080") Response.Write("selected");%>>#008080</option>
          <option style="COLOR: #d8bfd8; BACKGROUND-COLOR: #d8bfd8" value=#D8BFD8 <%if(TitleColor=="#D8BFD8") Response.Write("selected");%>>#D8BFD8</option>
          <option style="COLOR: #ff6347; BACKGROUND-COLOR: #ff6347" value=#FF6347 <%if(TitleColor=="#FF6347") Response.Write("selected");%>>#FF6347</option>
          <option style="COLOR: #40e0d0; BACKGROUND-COLOR: #40e0d0" value=#40E0D0 <%if(TitleColor=="#40E0D0") Response.Write("selected");%>>#40E0D0</option>
          <option style="COLOR: #ee82ee; BACKGROUND-COLOR: #ee82ee" value=#EE82EE <%if(TitleColor=="#EE82EE") Response.Write("selected");%>>#EE82EE</option>
          <option style="COLOR: #f5deb3; BACKGROUND-COLOR: #f5deb3" value=#F5DEB3 <%if(TitleColor=="#F5DEB3") Response.Write("selected");%>>#F5DEB3</option>
          <option style="COLOR: #ffffff; BACKGROUND-COLOR: #ffffff" value=#FFFFFF <%if(TitleColor=="#FFFFFF") Response.Write("selected");%>>#FFFFFF</option>
          <option style="COLOR: #f5f5f5; BACKGROUND-COLOR: #f5f5f5" value=#F5F5F5 <%if(TitleColor=="#F5F5F5") Response.Write("selected");%>>#F5F5F5</option>
          <option style="COLOR: #ffff00; BACKGROUND-COLOR: #ffff00" value=#FFFF00 <%if(TitleColor=="#FFFF00") Response.Write("selected");%>>#FFFF00</option>
          <option style="COLOR: #9acd32; BACKGROUND-COLOR: #9acd32" value=#9ACD32 <%if(TitleColor=="#9ACD32") Response.Write("selected");%>>#9ACD32</option>
          </select>